### ISSUE TITLE
new repdat + imd format

### ISSUE THREAD

**Issue by SalomeRonja** [rinikerlab/reeds#47]
In the new parallel GromosXX RE-EDS code, the format of the repdat output file changed slightly. When a new repdat is parsed with the pygromos file parser, I get the following error message:

```
Traceback (most recent call last):
  File "job_analysis.py", line 76, in <module>
    do_Reeds_analysis(in_folder=in_folder, out_folder=out_folder, gromos_path=gromos_path, topology=topology, in_ene_ana_lib=in_ene_ana_lib, in_imd=in_imd, optimized_eds_state_folder=optimized_eds_state_folder, state_undersampling_occurrence_potential_threshold=state_undersampling_occurrence_potential_threshold, state_physical_occurrence_potential_threshold=state_physical_occurrence_potential_threshold, undersampling_frac_thresh=undersampling_frac_thresh, grom_file_prefix=grom_file_prefix, title_prefix=title_prefix, n_processors=n_processors, verbose=verbose, control_dict=control_dict, )
  File "/cluster/work/igc/wsalome/code/reeds/reeds/function_libs/pipeline/worker_scripts/analysis_workers/RE_EDS_general_analysis.py", line 303, in do_Reeds_analysis
    boundary_conditions=boundary_conditions)
  File "/cluster/work/igc/wsalome/code/reeds/reeds/function_libs/file_management/file_management.py", line 1266, in reeds_project_concatenation
    repdat_file_paths=repdat_file_paths, verbose=verbose)
  File "/cluster/work/igc/wsalome/code/reeds/reeds/function_libs/file_management/file_management.py", line 208, in thread_worker_concat_repdat
    repdat_file = repdat.Repdat(repdat_file_paths.pop(0))  # repdat Class
  File "/cluster/work/igc/wsalome/code/reeds/reeds/submodules/pygromos/pygromos/files/repdat.py", line 48, in __init__
    system, data = parser.read_repdat(input_path, Vj_header=True)
  File "/cluster/work/igc/wsalome/code/reeds/reeds/submodules/pygromos/pygromos/files/_basics/parser.py", line 608, in read_repdat
    df = df.astype({'ID': 'int32', 'partner': 'int32', 'run': 'int32','s': 'int32'})
  File "/cluster/work/igc/wsalome/anaconda3/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 5526, in astype
    "Only a column name can be used for the "
KeyError: 'Only a column name can be used for the key in a dtype mappings argument.'
```

The issue can be solved by doing the renaming `df.rename(columns={"coord_ID": "ID"}, inplace=True)`. 

What I don't understand is line `df.rename(columns={"exch": "s"}, inplace=True)`. In the old repdat format, there is a column called `exch`, which contains booleans that encode whether the exchange between two replicas was accepted or rejected. The same column is still present in the new format, and it doesn't correspond to the s-values. @SchroederB do you know what the idea behind this is?

**Comment by SchroederB** [comment]
was merged :)

**Comment by SchroederB** [comment]
sorry just read the last sentence of your post

**Comment by SalomeRonja** [comment]
Yeah, it's low priority, but now that we're making the switch to the new code/repdat format, I think it would be nicer if we avoided the work of increasing all the replica indices in the repdat, and directly used the indices starting at 0 instead of 1 for the whole s-optimization analysis.

**Comment by candidechamp** [comment]
@SalomeRonja Do you still want to keep this issue open? I think everyone has been using the new gromosXX code and repdat file fomat/parser now and it's been working well. 

I'm not sure if the indexing change you mention was done or not though.
